---
functional:
  - Сайт должен иметь открытый исход
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть удобным на мобильном устройстве
  - Игры должны быть на различных языках
  - Возможность играть с рандомным соперником, выбранным самим игроком соперником или ботом
  - Возможность выбрать уровень сложности  
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Кнопка начала батла должна быть красного цвета
  - На сайте должен быть рейтинг игроков
  - Игра проходит в режиме реального времени
